# Generated by cpp11: do not edit by hand

cpp_version <- function() {
  .Call(`_rjsoncons_cpp_version`)
}

cpp_jsonpath <- function(data, path) {
  .Call(`_rjsoncons_cpp_jsonpath`, data, path)
}

cpp_jmespath <- function(data, path) {
  .Call(`_rjsoncons_cpp_jmespath`, data, path)
}
