# Generated by cpp11: do not edit by hand

cpp_j_flatten <- function(data, data_type, object_names, as, path, path_type) {
  .Call(`_rjsoncons_cpp_j_flatten`, data, data_type, object_names, as, path, path_type)
}

cpp_j_flatten_con <- function(con, data_type, object_names, as, path, path_type, n_records, verbose) {
  .Call(`_rjsoncons_cpp_j_flatten_con`, con, data_type, object_names, as, path, path_type, n_records, verbose)
}

cpp_j_patch_apply <- function(data, data_type, patch, as) {
  .Call(`_rjsoncons_cpp_j_patch_apply`, data, data_type, patch, as)
}

cpp_j_patch_from <- function(data_x, data_type_x, data_y, data_type_y, as) {
  .Call(`_rjsoncons_cpp_j_patch_from`, data_x, data_type_x, data_y, data_type_y, as)
}

cpp_j_patch_print <- function(patch, indent, width) {
  .Call(`_rjsoncons_cpp_j_patch_print`, patch, indent, width)
}

cpp_version <- function() {
  .Call(`_rjsoncons_cpp_version`)
}

cpp_as_r <- function(data, data_type, object_names) {
  .Call(`_rjsoncons_cpp_as_r`, data, data_type, object_names)
}

cpp_as_r_con <- function(con, data_type, object_names, n_records, verbose) {
  .Call(`_rjsoncons_cpp_as_r_con`, con, data_type, object_names, n_records, verbose)
}

cpp_j_query <- function(data, data_type, object_names, as, path, path_type) {
  .Call(`_rjsoncons_cpp_j_query`, data, data_type, object_names, as, path, path_type)
}

cpp_j_query_con <- function(con, data_type, object_names, as, path, path_type, n_records, verbose) {
  .Call(`_rjsoncons_cpp_j_query_con`, con, data_type, object_names, as, path, path_type, n_records, verbose)
}

cpp_j_pivot <- function(data, data_type, object_names, as, path, path_type) {
  .Call(`_rjsoncons_cpp_j_pivot`, data, data_type, object_names, as, path, path_type)
}

cpp_j_pivot_con <- function(con, data_type, object_names, as, path, path_type, n_records, verbose) {
  .Call(`_rjsoncons_cpp_j_pivot_con`, con, data_type, object_names, as, path, path_type, n_records, verbose)
}

cpp_j_schema_is_valid <- function(data, schema) {
  .Call(`_rjsoncons_cpp_j_schema_is_valid`, data, schema)
}

cpp_j_schema_validate <- function(data, schema, as) {
  .Call(`_rjsoncons_cpp_j_schema_validate`, data, schema, as)
}
