on:
  push:
    paths: ['vignettes/**.Rmd']

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-renv@v1

      - name: Query dependencies
        run: |
          install.packages(c("remotes", "rmarkdown", "BiocManager"))
        shell: Rscript {0}

      - name: Install Dependencies
        run: |
          options(repos = c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"))
          BiocManager::install(version = "devel", ask = FALSE)
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          remotes::install_local(repos = BiocManager::repositories())
        shell: Rscript {0}

      - name: Render README
        run: |
          Rscript -e 'rmarkdown::render(input = "inst/scripts/README.Rmd", output_dir = ".")'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit -m 'Re-build README.md file'
          git push origin
